<?php

namespace Database\Seeders;

use App\Models\PageContent;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PageContentSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $rows = [
            [
                'type' => 'about',
                'locale' => 'tr',
                'content' => [
                    'hero_eyebrow' => 'Hakkımızda',
                    'hero_title' => 'Teknolojide<br/>Yeni Bir Perspektif',
                    'hero_lede' => 'Ovion; ileri teknolojiyi, güçlü mühendisliği ve modern tasarımı bir araya getiren yeni nesil bir teknoloji markasıdır. Her ürünümüzde kalite, performans ve kullanıcı deneyimini ön planda tutarak teknolojiyi günlük yaşamın ayrılmaz bir parçası haline getiriyoruz.',
                    'stats' => [
                        ['value' => '200+', 'label' => 'Çalışan'],
                        ['value' => '5', 'label' => 'Ürün ailesi'],
                        ['value' => '81', 'label' => 'İlde servis ağı'],
                    ],
                    'story_year' => 'Gelecek',
                    'story_year_lbl' => 'Yenilikten Güç Alıyoruz',
                    'story_eyebrow' => 'Hikayemiz',
                    'story_title' => 'Yenilikten güç alan,<br/>geleceği şekillendiren bir marka.',
                    'story_p1' => 'Ovion, yalnızca gelişmeleri takip etmekle kalmayıp geleceğin ihtiyaçlarını öngören bir marka olma hedefiyle hareket eder. Ürün geliştirme süreçlerimizin temelinde kullanıcı deneyimi, sürdürülebilir kalite ve sürekli yenilik anlayışı yer alır.',
                    'story_p2' => 'Tasarımdan üretime, yazılım optimizasyonundan kalite kontrole kadar her adımı en yüksek standartlarda yürütüyor; kullanıcılarımızın beklentilerini aşan ürünler geliştirmeyi hedefliyoruz.',
                    'values_eyebrow' => 'Değerlerimiz',
                    'values_title' => 'Her cihazımızı şekillendiren<br/>üç temel ilke.',
                    'values' => [
                        ['title' => 'Performans', 'desc' => 'Her Ovion ürünü, günlük kullanımın en zorlu koşullarına dayanacak şekilde optimize edilmiş donanım ve yazılım bileşenleriyle tasarlanır.'],
                        ['title' => 'Güvenilirlik', 'desc' => 'Kapsamlı test süreçlerinden geçirilen her cihaz, uzun ömürlü ve tutarlı bir deneyim sunar. Kalite standartlarımızdan taviz vermeyiz.'],
                        ['title' => 'Yenilik', 'desc' => 'Uzman mühendis ve tasarımcı ekiplerimiz, her yeni modelde kullanıcı deneyimini bir adım daha ileriye taşıyacak teknolojiler geliştirmek için çalışır.'],
                    ],
                    'made_eyebrow' => 'Üretim & Kalite',
                    'made_title' => 'Türkiye\'de tasarlandı.<br/><em>Türkiye\'de</em> üretildi.',
                    'made_sub' => 'Her Ovion cihazı; modern üretim teknolojileri ve kapsamlı kalite kontrol süreçleriyle hayata geçirilir. Üretimin her aşamasında kalite, güvenilirlik ve dayanıklılık ilkeleri ön planda tutulur.',
                    'cta_eyebrow' => 'Geleceği Birlikte İnşa Edelim',
                    'cta_title' => 'Bugün attığımız her adım,<br/>yarının teknolojisini şekillendirir.',
                    'cta_sub' => 'Ovion olarak başarıyı yalnızca ticari sonuçlarla değil, yarattığımız kalıcı değerle ölçüyoruz. Güven, şeffaflık ve yenilikçilikle teknoloji ekosistemine katkı sağlarken geleceğe bugünden hazırlanıyoruz.',
                ],
            ],
            [
                'type' => 'about',
                'locale' => 'en',
                'content' => [
                    'hero_eyebrow' => 'About Us',
                    'hero_title' => 'A New Perspective<br/>on Technology',
                    'hero_lede' => 'Ovion is a next-generation technology brand uniting advanced engineering, innovative design, and smart software. We build products that make quality and performance an inseparable part of everyday life.',
                    'stats' => [
                        ['value' => '200+', 'label' => 'Employees'],
                        ['value' => '5', 'label' => 'Product lines'],
                        ['value' => '81', 'label' => 'Cities with service'],
                    ],
                    'story_year' => 'Future',
                    'story_year_lbl' => 'Powered by Innovation',
                    'story_eyebrow' => 'Our Story',
                    'story_title' => 'Powered by innovation,<br/>built for the future.',
                    'story_p1' => 'Ovion doesn\'t just follow technological developments — we anticipate the needs of tomorrow. User experience, sustainable quality, and continuous improvement are at the core of everything we build.',
                    'story_p2' => 'From design to production, from software to quality control, every step is executed at the highest standard — so our products don\'t just meet expectations, they exceed them.',
                    'values_eyebrow' => 'Our Values',
                    'values_title' => 'Three principles behind<br/>every product we build.',
                    'values' => [
                        ['title' => 'Performance', 'desc' => 'Every Ovion product is engineered with optimized hardware and software to handle the demands of daily use — reliably, and without compromise.'],
                        ['title' => 'Reliability', 'desc' => 'Each device passes comprehensive testing before reaching your hands. Consistent quality over time isn\'t a goal — it\'s our standard.'],
                        ['title' => 'Innovation', 'desc' => 'Our engineering and design teams work to push every new model further — translating cutting-edge technology into meaningful, real-world solutions.'],
                    ],
                    'made_eyebrow' => 'Manufacturing & Quality',
                    'made_title' => 'Designed in Türkiye.<br/><em>Made</em> in Türkiye.',
                    'made_sub' => 'Every Ovion device is brought to life through modern manufacturing technologies and rigorous quality control. At every stage of production, quality, reliability, and durability remain non-negotiable.',
                    'cta_eyebrow' => 'Let\'s Build Tomorrow Together',
                    'cta_title' => 'Every step we take today<br/>shapes the technology of tomorrow.',
                    'cta_sub' => 'At Ovion, success is measured not just by results, but by the lasting value we create. Grounded in trust, transparency, and innovation, we contribute to the technology ecosystem while always thinking ahead.',
                ],
            ],
            [
                'type' => 'support',
                'locale' => 'tr',
                'content' => [
                    'hero_eyebrow' => 'Destek',
                    'hero_title' => 'Nasıl yardımcı<br/>olabiliriz?',
                    'hero_sub' => 'Garanti sorgulama, servis talebi, kılavuz veya teknik destek — doğru yere geldiniz.',
                    'quick_eyebrow' => 'Hızlı Erişim',
                    'quick_title' => 'Ne yapmak istiyorsunuz?',
                    'war_eyebrow' => 'Garanti',
                    'war_title' => '24 ay güvenceli<br/>kullanım.',
                    'war_desc' => 'Ovion, tüm ürünlerini 24 aylık Türkiye garantisiyle teslim eder. Yerli üretimin avantajıyla yedek parça teminini çok daha hızlı sağlıyor ve garanti süreçlerini tamamen dijitalleştiriyoruz.',
                    'warranty_list' => [
                        ['text' => 'Üretim kaynaklı donanım arızaları'],
                        ['text' => 'Yazılım ve sistem sorunları'],
                        ['text' => 'Batarya kapasitesi (normal kullanımda %80 altı)'],
                        ['text' => 'Ekran ve kamera modülü fabrika hataları'],
                        ['text' => 'Şarj portu ve fiziksel düğme arızaları'],
                    ],
                    'war_badge' => 'Türkiye Garantisi',
                    'war_months' => '24',
                    'war_unit' => 'ay',
                    'war_sub' => 'Tüm Ovion ürünleri için standart garanti süresi',
                    'war_row1_lbl' => 'Servis süresi',
                    'war_row1_val' => 'Ortalama 3 iş günü',
                    'war_row2_lbl' => 'Yetkili servis',
                    'war_row2_val' => '200+ nokta',
                    'war_row3_lbl' => 'Kargo desteği',
                    'war_row3_val' => 'Garanti kapsamında ücretsiz',
                    'steps_eyebrow' => 'Servis Süreci',
                    'steps_title' => 'Servis talebi<br/>4 adımda tamamlanır.',
                    'service_steps' => [
                        ['title' => 'Talep Oluştur', 'desc' => 'Web veya uygulama üzerinden servis talebi oluşturun. Sorununuzu kısa bir notla açıklayın.'],
                        ['title' => 'Kargo veya Servis', 'desc' => 'Cihazınızı en yakın servise götürün ya da kapıdan kargo ile gönderin; karşılıklı teslim ücretsizdir.'],
                        ['title' => 'Teşhis ve Onarım', 'desc' => 'Uzman teknisyenlerimiz cihazı inceler, size teşhis raporu gönderir ve onayınızla onarıma başlar.'],
                        ['title' => 'Teslim', 'desc' => 'Ortalama 3 iş günü içinde cihazınız kapınıza teslim edilir. Süreç SMS ve e-posta ile takip edilebilir.'],
                    ],
                    'contact_eyebrow' => 'İletişim',
                    'contact_title' => 'Uzmanlarımız<br/>her zaman burada.',
                ],
            ],
            [
                'type' => 'support',
                'locale' => 'en',
                'content' => [
                    'hero_eyebrow' => 'Support',
                    'hero_title' => 'How can we<br/>help you?',
                    'hero_sub' => 'Warranty check, service request, user manual or technical support — you\'ve come to the right place.',
                    'quick_eyebrow' => 'Quick Access',
                    'quick_title' => 'What would you like to do?',
                    'war_eyebrow' => 'Warranty',
                    'war_title' => '24 months of<br/>secured use.',
                    'war_desc' => 'Ovion delivers all its products with a 24-month Türkiye warranty. Thanks to domestic manufacturing, we provide spare parts faster and have fully digitalised our warranty processes.',
                    'warranty_list' => [
                        [
                            'text' => 'Manufacturing-related hardware faults',
                        ],
                        [
                            'text' => 'Software and system issues',
                        ],
                        [
                            'text' => 'Battery capacity (below 80% under normal use)',
                        ],
                        [
                            'text' => 'Screen and camera module factory defects',
                        ],
                        [
                            'text' => 'Charging port and physical button faults',
                        ],
                    ],
                    'war_badge' => 'Türkiye Warranty',
                    'war_months' => '24',
                    'war_unit' => 'mo.',
                    'war_sub' => 'Standard warranty period for all Ovion products',
                    'war_row1_lbl' => 'Service time',
                    'war_row1_val' => '~3 business days',
                    'war_row2_lbl' => 'Authorised service',
                    'war_row2_val' => '200+ locations',
                    'war_row3_lbl' => 'Shipping support',
                    'war_row3_val' => 'Free under warranty',
                    'steps_eyebrow' => 'Service Process',
                    'steps_title' => 'Service request<br/>completed in 4 steps.',
                    'service_steps' => [
                        [
                            'title' => 'Create Request',
                            'desc' => 'Create a service request via web or app. Briefly describe your issue.',
                        ],
                        [
                            'title' => 'Drop-off or Courier',
                            'desc' => 'Drop your device off at the nearest service centre or send it by courier; round-trip delivery is free.',
                        ],
                        [
                            'title' => 'Diagnosis and Repair',
                            'desc' => 'Our expert technicians inspect the device, send you a diagnostic report and start the repair upon your approval.',
                        ],
                        [
                            'title' => 'Delivery',
                            'desc' => 'On average within 3 business days, your device is delivered to your door. The process can be tracked via SMS and email.',
                        ],
                    ],
                    'contact_eyebrow' => 'Contact',
                    'contact_title' => 'Our experts<br/>are always here.',
                ],
            ],
            [
                'type' => 'home',
                'locale' => 'tr',
                'content' => [
                    'home_hero' => [
                        [
                            'image' => null,
                            'badge_text' => 'Yeni — V20 Pro',
                            'title' => 'Teknolojiyle<br/>gelen <em>deneyim.</em>',
                            'description' => '',
                            'cta_text' => 'Detaylı İncele',
                            'cta_url' => '/telefonlar/v20-pro',
                        ],
                        [
                            'image' => null,
                            'badge_text' => '',
                            'title' => 'Vio Watch Curved',
                            'description' => '',
                            'cta_text' => '',
                            'cta_url' => '',
                        ],
                    ],
                    'home_stats' => [
                        [
                            'value' => '3',
                            'suffix' => '',
                            'label' => 'Ürün kategorisi',
                        ],
                        [
                            'value' => '81',
                            'suffix' => '',
                            'label' => 'İlde servis ağı',
                        ],
                        [
                            'value' => '200',
                            'suffix' => '+',
                            'label' => 'Çalışan · İstanbul',
                        ],
                        [
                            'value' => '2',
                            'suffix' => ' yıl',
                            'label' => 'Standart garanti',
                        ],
                    ],
                    'home_scroll' => [
                        [
                            'image' => null,
                            'eyebrow' => 'Telefon — V Serisi',
                            'title' => 'Akıllı Telefonlar',
                            'description' => 'V serisi ile günlük yaşamı kolaylaştıran, Türkiye\'de tasarlanmış ve üretilmiş telefon deneyimi. 90 Hz ekran, 50 MP AI kamera ve 5000 mAh batarya.',
                            'btn_text' => 'V11 Lite\'ı Keşfet',
                            'btn_url' => '/telefonlar/v11-lite',
                        ],
                        [
                            'image' => null,
                            'eyebrow' => 'Saat — S Serisi',
                            'title' => 'Akıllı Saatler',
                            'description' => 'S serisi ile sağlığınızı, adımlarınızı ve uyku düzeninizi gerçek zamanlı takip edin. AMOLED ekran, GPS ve 14 günlük pil ömrü.',
                            'btn_text' => 'S3 Pro\'yu Keşfet',
                            'btn_url' => '/saatler/s3-pro',
                        ],
                        [
                            'image' => null,
                            'eyebrow' => 'Kulaklık — H Serisi',
                            'title' => 'Kulaklıklar',
                            'description' => 'H serisi ile Hi-Fi ses kalitesi ve hibrit ANC bir arada. 30 saatlik pil ömrüyle müziğinize kesintisiz odaklanın.',
                            'btn_text' => 'H1 Pro\'yu Keşfet',
                            'btn_url' => '/kulakliklar/h1-pro',
                        ],
                    ],
                    'home_showcase_kicker' => 'Koleksiyon',
                    'home_showcase_title' => 'Tüm Ürünler',
                    'home_showcase_tab_all' => 'Tümü',
                    'home_showcase_link_text' => 'Daha fazlası için',
                    'home_feat_title' => 'Ovion: Güçlü Teknoloji,<br>Her İhtiyaca Uygun Tasarım',
                    'home_feat_cards' => [
                        [
                            'size' => 'wide',
                            'color' => 'amber',
                            'reverse' => false,
                            'image' => null,
                            'title' => 'Gün Boyu Güç',
                            'description' => 'Uzun ömürlü batarya teknolojisi ve hızlı şarj desteğiyle tüm Ovion ürünleri sizi hiç şarjsız bırakmaz.',
                        ],
                        [
                            'size' => 'narrow',
                            'color' => 'none',
                            'reverse' => false,
                            'image' => null,
                            'title' => 'Üst Segment Performans',
                            'description' => 'Son nesil işlemciler ve optimize edilmiş yazılımla Ovion cihazları hem hız hem de verimlilik konusunda rakiplerinin önünde.',
                        ],
                        [
                            'size' => 'narrow',
                            'color' => 'none',
                            'reverse' => false,
                            'image' => null,
                            'title' => 'Göz Alıcı Ekranlar',
                            'description' => 'AMOLED paneller, yüksek yenileme hızı ve akıllı parlaklık yönetimiyle Ovion ekranları her ortamda mükemmel görüntü sunar.',
                        ],
                        [
                            'size' => 'wide',
                            'color' => 'indigo',
                            'reverse' => true,
                            'image' => null,
                            'title' => 'Akıllı Bağlantı',
                            'description' => 'NFC, 5G, Bluetooth 5.3 ve Dual SIM desteğiyle Ovion ürünleri sizi her an dijital dünyaya bağlar; ödeme ve paylaşım kolaylaşır.',
                        ],
                    ],
                    'home_trust_eyebrow' => 'Ovion Güvencesi',
                    'home_trust_title' => 'Satın aldıktan<br/>sonra da yanınızdayız.',
                    'home_trust_cards' => [
                        [
                            'title' => 'Resmi Garanti',
                            'link_url' => '',
                            'description' => 'Tüm Ovion ürünlerinde standart 2 yıl resmi Türkiye garantisi. Satın aldığınız günden itibaren geçerli.',
                            'link_text' => '',
                        ],
                        [
                            'title' => 'Yetkili Servis',
                            'link_url' => '',
                            'description' => 'Türkiye\'nin 81 ilinde yetkili Ovion servis noktası. Onarım için en yakın servisi kolayca bulun.',
                            'link_text' => '',
                        ],
                        [
                            'title' => 'Türkiye\'de Üretim',
                            'link_url' => '',
                            'description' => 'Her ürün İstanbul\'da tasarlanır, Türkiye\'deki üretim tesisimizde üretilir. Yerli sertifikalı.',
                            'link_text' => '',
                        ],
                        [
                            'title' => 'Müşteri Desteği',
                            'link_url' => '/destek',
                            'description' => 'Telefon, e-posta ve canlı sohbet ile 7/24 destek ekibimize ulaşın. Sorularınız cevapsız kalmaz.',
                            'link_text' => 'Destek Merkezi',
                        ],
                    ],
                    'home_buy_title' => 'Satın almaya hazır mısınız?',
                    'home_buy_price' => '₺4.999\'dan başlayan fiyatlarla',
                    'home_buy_shipping' => 'ücretsiz kargo · 24 ay garanti',
                    'home_buy_cta1_text' => 'Satın Al',
                    'home_buy_cta1_url' => '#products',
                    'home_buy_cta2_text' => 'Bayi Bul',
                    'home_buy_cta2_url' => '/destek',
                ],
            ],
            [
                'type' => 'home',
                'locale' => 'en',
                'content' => [
                    'home_hero' => [
                        [
                            'image' => null,
                            'badge_text' => 'New — V20 Pro',
                            'title' => 'Technology that<br/>shapes <em>experience.</em>',
                            'description' => '',
                            'cta_text' => 'Explore',
                            'cta_url' => '/en/phones/v20-pro',
                        ],
                        [
                            'image' => null,
                            'badge_text' => '',
                            'title' => 'Vio Watch Curved',
                            'description' => '',
                            'cta_text' => '',
                            'cta_url' => '',
                        ],
                    ],
                    'home_stats' => [
                        [
                            'value' => '3',
                            'suffix' => '',
                            'label' => 'Product categories',
                        ],
                        [
                            'value' => '81',
                            'suffix' => '',
                            'label' => 'Cities with service',
                        ],
                        [
                            'value' => '200',
                            'suffix' => '+',
                            'label' => 'Employees · Istanbul',
                        ],
                        [
                            'value' => '2',
                            'suffix' => ' yr',
                            'label' => 'Standard warranty',
                        ],
                    ],
                    'home_scroll' => [
                        [
                            'image' => null,
                            'eyebrow' => 'Phone — V Series',
                            'title' => 'Smartphones',
                            'description' => 'V-series phones, designed and made in Türkiye, simplify your daily life. 90 Hz display, 50 MP AI camera and 5000 mAh battery.',
                            'btn_text' => 'Discover V11 Lite',
                            'btn_url' => '/en/phones/v11-lite',
                        ],
                        [
                            'image' => null,
                            'eyebrow' => 'Watch — S Series',
                            'title' => 'Smartwatches',
                            'description' => 'Track your health, steps and sleep in real time with the S series. AMOLED display, GPS and 14-day battery life.',
                            'btn_text' => 'Discover S3 Pro',
                            'btn_url' => '/en/watches/s3-pro',
                        ],
                        [
                            'image' => null,
                            'eyebrow' => 'Headphones — H Series',
                            'title' => 'Headphones',
                            'description' => 'H-series brings together Hi-Fi sound and hybrid ANC. 30-hour battery keeps you focused on your music.',
                            'btn_text' => 'Discover H1 Pro',
                            'btn_url' => '/en/headphones/h1-pro',
                        ],
                    ],
                    'home_showcase_kicker' => 'Collection',
                    'home_showcase_title' => 'All Products',
                    'home_showcase_tab_all' => 'All',
                    'home_showcase_link_text' => 'Learn more',
                    'home_feat_title' => 'Ovion: Powerful Technology,<br>Designed for Every Need',
                    'home_feat_cards' => [
                        [
                            'size' => 'wide',
                            'color' => 'amber',
                            'reverse' => false,
                            'image' => null,
                            'title' => 'All-Day Power',
                            'description' => 'Long-lasting battery technology and fast charging mean Ovion products never leave you without power.',
                        ],
                        [
                            'size' => 'narrow',
                            'color' => 'none',
                            'reverse' => false,
                            'image' => null,
                            'title' => 'Top-Tier Performance',
                            'description' => 'Latest-generation processors and optimised software put Ovion devices ahead in both speed and efficiency.',
                        ],
                        [
                            'size' => 'narrow',
                            'color' => 'none',
                            'reverse' => false,
                            'image' => null,
                            'title' => 'Stunning Displays',
                            'description' => 'AMOLED panels, high refresh rates and smart brightness deliver perfect picture quality in every environment.',
                        ],
                        [
                            'size' => 'wide',
                            'color' => 'indigo',
                            'reverse' => true,
                            'image' => null,
                            'title' => 'Smart Connectivity',
                            'description' => 'NFC, 5G, Bluetooth 5.3 and Dual SIM keep you connected at all times — payments and sharing made effortless.',
                        ],
                    ],
                    'home_trust_eyebrow' => 'The Ovion Guarantee',
                    'home_trust_title' => 'We are with you<br/>after the purchase, too.',
                    'home_trust_cards' => [
                        [
                            'title' => 'Official Warranty',
                            'link_url' => '',
                            'description' => 'A standard 2-year official Türkiye warranty on all Ovion products. Valid from the day of purchase.',
                            'link_text' => '',
                        ],
                        [
                            'title' => 'Authorised Service',
                            'link_url' => '',
                            'description' => 'Authorised Ovion service points across all 81 provinces of Türkiye. Easily find the nearest one for repairs.',
                            'link_text' => '',
                        ],
                        [
                            'title' => 'Made in Türkiye',
                            'link_url' => '',
                            'description' => 'Every product is designed in Istanbul and produced in our domestic facility. Locally certified.',
                            'link_text' => '',
                        ],
                        [
                            'title' => 'Customer Support',
                            'link_url' => '/en/support',
                            'description' => 'Reach our team 24/7 via phone, email and live chat. Your questions never go unanswered.',
                            'link_text' => 'Support Centre',
                        ],
                    ],
                    'home_buy_title' => 'Ready when you are.',
                    'home_buy_price' => 'From ₺4,999',
                    'home_buy_shipping' => 'free shipping in Türkiye · 24-month warranty',
                    'home_buy_cta1_text' => 'Configure & buy',
                    'home_buy_cta1_url' => '#products',
                    'home_buy_cta2_text' => 'Find a reseller',
                    'home_buy_cta2_url' => '/en/support',
                ],
            ],
            [
                'type' => 'accessories',
                'locale' => 'tr',
                'content' => [
                    'hero_eyebrow' => 'Aksesuarlar',
                    'hero_title' => 'Her detayda<br /><em>Ovion kalitesi.</em>',
                    'hero_lede' => 'Cihazlarınızı korumak, şarj etmek ve kişiselleştirmek için tasarlanmış aksesuarlar. Ovion ürünleriyle mükemmel uyum.',
                    'cta_all_text' => 'Tümünü İncele',
                    'cta_device_text' => 'Cihazıma Göre Bul',
                    'spot_eyebrow' => 'Öne Çıkan',
                    'spot_title' => 'Koruma ve<br />zariflik bir arada.',
                    'grid_eyebrow' => 'Tüm Aksesuarlar',
                    'grid_title' => 'Koleksiyonu keşfet.',
                    'cta_eyebrow' => 'Aksesuar Dünyası',
                    'cta_title' => 'Ovion\'u<br /><em>tamamla.</em>',
                    'cta_desc' => 'Cihazlarınızın performansını ve görünümünü bir üst seviyeye taşıyın. Tüm ürünler Ovion garantisi ile sunulur.',
                    'cta_btn1_text' => 'Destek Merkezi',
                    'cta_btn1_url' => '/destek',
                    'cta_btn2_text' => 'Anasayfa',
                    'cta_btn2_url' => '/',
                ],
            ],
            [
                'type' => 'accessories',
                'locale' => 'en',
                'content' => [
                    'hero_eyebrow' => 'Accessories',
                    'hero_title' => 'Ovion quality<br /><em>in every detail.</em>',
                    'hero_lede' => 'Accessories designed to protect, charge and personalise your devices. A perfect fit for Ovion products.',
                    'cta_all_text' => 'View All',
                    'cta_device_text' => 'Find by Device',
                    'spot_eyebrow' => 'Featured',
                    'spot_title' => 'Protection and<br />elegance together.',
                    'grid_eyebrow' => 'All Accessories',
                    'grid_title' => 'Explore the collection.',
                    'cta_eyebrow' => 'Accessory World',
                    'cta_title' => 'Complete<br /><em>your Ovion.</em>',
                    'cta_desc' => 'Take your devices\' performance and look to the next level. All products come with the Ovion warranty.',
                    'cta_btn1_text' => 'Support Centre',
                    'cta_btn1_url' => '/en/support',
                    'cta_btn2_text' => 'Home',
                    'cta_btn2_url' => '/en',
                ],
            ],
        ];

        foreach ($rows as $row) {
            PageContent::updateOrCreate(
                ['type' => $row['type'], 'locale' => $row['locale']],
                ['content' => $row['content']],
            );
        }
    }
}
